###
# POST 
# REGISTER endpoint
POST http://localhost/aptech/techies-api/api/register.php

{
    "firstname":"Prof4",
    "lastname": "Cain",
    "email":"prof4@gmail.com",
    "password":"prof4000"
}




###
# POST 
# LOGIN endpoint
POST http://localhost/aptech/techies-api/api/login.php

{
    "email":"prof4@gmail.com",
    "password":"prof4000"
}




###
# GET 
# LOG OUT endpoint
GET http://localhost/aptech/techies-api/api/logout.php HTTP/1.1




###
# GET 
# LOG OUT endpoint
GET http://localhost/aptech/techies-api/api/logout.php