###
# POST 
# REGISTER endpoint
POST http://localhost/aptech/techies-api/api/register.php

{
    "firstname":"Prof2",
    "lastname": "Bella",
    "email":"prof2@gmail.com",
    "password":"prof2000"
}





###
# POST 
# LOGIN endpoint
POST http://localhost/aptech/techies-api/api/login.php

{
    "email":"prof2@gmail.com",
    "password":"prof2000"
}




###
# GET 
# LOG OUT endpoint
GET http://localhost/aptech/techies-api/api/logout.php

